---
- name: Create temp file
  tempfile:
    state: file
  register: project_request_tempfile

- name: Generate project request template
  shell: "oc adm create-bootstrap-project-template -o yaml >{{ project_request_tempfile.path }}"

- name: Update project request template with project objects
  lineinfile:
    insertbefore: '^parameters:'
    line: "{{ default_project_objects }}"
    path: "{{ project_request_tempfile.path }}"

# - name: Add node-selector annotation
#   lineinfile:
#     regexp: '^( *)(openshift.io/description: .+)$'
#     line: '\1\2\n\1openshift.io/node-selector: env=app,client=common'
#     path: "{{ project_request_tempfile.path }}"
#     backrefs: true

- name: Delete existing project request template
  shell: "oc delete -n default -f {{ project_request_tempfile.path }} --ignore-not-found"

- name: Create new project request template
  shell: "oc create -n default -f {{ project_request_tempfile.path }}"

- name: Label default project
  shell: "oc label namespace default name=default --overwrite"
  
- name: Clean up tempfile
  file:
    path: "{{ project_request_tempfile.path }}"
    state: absent

