---
# - name: Ensure ansible connectivity
#   hosts: all
#   gather_facts: false
#   tasks:
#   - ping:

# - name: Update all packages
#   hosts: all
#   gather_facts: false
#   tasks:
#   - yum:
#       name: '*'
#       state: 'latest'

# - name: Ensure docker is running on nodes
#   hosts: nodes
#   tasks:
#   - shell: 'systemctl status docker | grep Active'

# - name: Standard OpenShift Ansible Prerequisites Playbook
#   include_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

# - name: Standard OpenShift Ansible Deploy Cluster Playbook
#   include_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

# - name: Deploy MitziCom OpenShift Container Platform Environment
#   hosts: all
#   gather_facts: false
#   roles:
#   - role: openshift-applier

# - name: Configure NFS Export Directories
#   hosts: nfs
#   gather_facts: false
#   vars_files:
#   - vars/persistent_volumes.yml
#   roles:
#   - role: nfs-server

- name: Configure PVs
  hosts: masters[0]
  gather_facts: false
  vars_files:
  - vars/persistent_volumes.yml
  roles:
  - role: pv-registrar

